### ISSUE TITLE
Twig Form

### ISSUE THREAD

**Issue by acutting1755** [koftikes/symfony-adminlte-bundle#1]
There is currently an issue with the code when attempting to use this on new versions of symfony.  Twig Form is no longer valid it is now Twig Form_Themes resulting in 
if (isset($bundles['TwigBundle'])) {
            $container->prependExtensionConfig(
                'twig', [
                    'form_themes' =>  ['bootstrap_3_layout.html.twig']
                ]
            );
        }
to make the bundle begin to work.  This however will not work for older versions of symfony. I'm still working through other issues and will add issues as I goes.

**Comment by koftikes** [comment]
This issue was fixed and merge in master.
Thank you.
