### ISSUE TITLE
Replace assetic by webpack-encore

### ISSUE THREAD

**Issue by Manalro** [koftikes/symfony-adminlte-bundle#16]
In symfony docs, they indicate that starting from Symfony 2.8, Assetic is no longer included by default in the Symfony Standard Edition ( https://symfony.com/doc/3.4/frontend/assetic.html ). I want to know if you have any process that enables us to replace assetics by wepack-encore while configuring adminLTE.

**Comment by koftikes** [comment]
Yes I know.
Most likely in the next version I will refuse to use this extension.
But since the webpack does not know how to work with external bundles (or I haven’t yet defined how it does it), connected JS and CSS will be available which can be overridden.
Thank you for asking.
