### ISSUE TITLE
MenuBuilder shows only the last menu

### ISSUE THREAD

**Issue by aissasell** [koftikes/symfony-adminlte-bundle#17]
`public function getMenu(){
        $menu = [];
        //Menu Label
        $menu['label_main'] = new MenuItemModel('Main Navigation');

        //One Level Menu
        $menu['item_info'] = ( new MenuItemModel('Files'))
            ->setRoute('admin_list_files')
            ->setIcon('fa fa-circle-o text-blue')
            ->addBadge('17', MenuItemInterface::COLOR_RED)
            ->addBadge('new');

        //Multilevel Menu
        $menu['Files'] = (new MenuItemModel('Text Files'))
            ->setIcon('fa fa-circle-o')
            ->addChild(
                (new MenuItemModel('All Files'))
                    ->setRoute('admin_list_files')
            )
            ->addChild(
                (new MenuItemModel('Upload a new File'))
                    ->setRoute('admin_upload_file')
            );

        return $menu;
    }`

**Comment by DiegoPBorja** [comment]
i have some similar issue, in my case sidebar is blank and event never gets invoked

**Comment by koftikes** [comment]
I check it with next code and all works fine for me.
```
    protected function getMenu()
    {
        $menu               = [];
        $menu['label_main'] = new MenuItemModel('Main Navigation');
        $menu['item_info']  = (new MenuItemModel('Files'))
            ->setRoute('sbs_adminlte_user_profile')
            ->setIcon('fa fa-circle-o text-blue')
            ->addBadge('17', MenuItemInterface::COLOR_RED)
            ->addBadge('new');
        $menu['files']      = (new MenuItemModel('Text Files'))
            ->setIcon('fa fa-circle-o')
            ->addChild(
                (new MenuItemModel('All Files'))
                    ->setRoute('sbs_adminlte_all_notifications')
            )
            ->addChild(
                (new MenuItemModel('Upload a new File'))
                    ->setRoute('sbs_adminlte_all_tasks')
            );

        return $menu;
    }
```
Please use latest version of bundle and check again.
Thank you in advance.
