### ISSUE TITLE
Version 1.5.0 throws error when running "sbs:admin-lte:build-assets"

### ISSUE THREAD

**Issue by sudo-barun** [koftikes/symfony-adminlte-bundle#28]
symfony-adminlte-bundle version 1.5.0 installs successfully but throws error when running `sbs:admin-lte:build-assets`.

**To Reproduce**
1. Inside symfony 3.4 project, run `composer require sbs/symfony-adminlte-bundle=v1.5.0`.
1. Perform all configuration as mentioned in README file
1. Run `app/console sbs:admin-lte:build-assets`
1. See error in the console output below:
```

 // Trying to build AdminLTE bundle assets.

In Finder.php line 548:
                                    
  The "" directory does not exist.  
                                    

```

**Cause of error**
The error happens because it cannot find the directory for `seiyria-bootstrap-slider`. During the installation of `sbs/symfony-adminlte-bundle` 1.5.0, `almasaeed2010/adminlte` v2.4.3 is installed. The expected version of `almasaeed2010/adminlte` to be installed is v2.4.17 (or greater) as mentioned in commit db06b0a9b633f3a20b458d1a0d00d5f343377af3.

**Expected behavior**
`almasaeed2010/adminlte` v2.4.17 (or greater) should have been installed.

**Comment by koftikes** [comment]
This issue was fixed in new versions
