### ISSUE TITLE
DataTables version

### ISSUE THREAD

**Issue by jvbussel** [koftikes/symfony-adminlte-bundle#6]
Hi, 

Thanks fro this great bundle.

Currently I get in the plugins directory DataTables 1.10.7
But I want to have 1.10.15

What to do to get this latest version?

**Comment by koftikes** [comment]
Hello,
You can install it via composer and use as external js/css.
It's main reason why I not include all plugins by default.

**Comment by jvbussel** [comment]
Hi,

I currently installed the latest version using bower.

Maybe I do not understand the mechanism of bunldes well enough where it is decided in your bundle to install a specific version of DataTables. I did a grep but could not find a file mentioning the version of DataTables being installed by your bundle.

Regards,

Joop

**Comment by koftikes** [comment]
All pluging you can find in path `/web/bundles/sbsadminlte/plugins`.
But as I sais before they are not include in main js/css.
For include some else see documentations 
[./Resources/docs/layout.md#layout-blocks](https://github.com/koftikes/symfony-adminlte-bundle/blob/master/Resources/docs/layout.md#layout-blocks)

**Comment by jvbussel** [comment]
Hi,

I already found it. It is not your bundle which causes a specific version of DataTables to be installed. It is the AdminLTE bundle which is shipped with specific versions of plugins. I wished it had dependencies making it easier to update to newer versions.

Thanks again.
