### ISSUE TITLE
Set minimum-stability

### ISSUE THREAD

**Issue by matudelatower** [koftikes/symfony-adminlte-bundle#7]
when try to run `composer require sbs/symfony-adminlte-bundle` throws: 

<img width="1276" alt="captura de pantalla 2017-08-17 a la s 16 08 12" src="https://user-images.githubusercontent.com/5694115/29429266-7924f86e-8366-11e7-993e-6e1d55c5d9f2.png">

**Comment by koftikes** [comment]
Just add it to composer.json as  "sbs/symfony-adminlte-bundle": "dev-master" and run composer update command.

**Comment by matudelatower** [comment]
@koftikes yes, but with `composre update` command updates all my dependencies =/

**Comment by koftikes** [comment]
use  composer update sbs/*

**Comment by matudelatower** [comment]
It works, but in fact, the minimum-stability must be setted
